ignoreDependencies = ["@base-ui/react", "@orpc/client", "@orpc/shared", "class-variance-authority", "shadcn"]

ignorePatterns = [
  "**/*.test.ts",
  "**/*.test.tsx",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "vitest.config.mts",
  "vitest.setup.ts",
  "src/components/ui/**",
  "scripts/**",
]
